In [1]:
import pandas as pd
import numpy as np

In [2]:
# data  https://www.kaggle.com/datasets/ankurzing/sentiment-analysis-for-financial-news

df = pd.read_csv("all-data.csv", encoding = "latin-1")
df.head()

,neutral,"According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing ."
0,neutral,Technopolis plans to develop in stages an area...
1,negative,The international electronic industry company ...
2,positive,With the new production plant the company woul...
3,positive,According to the company 's updated strategy f...
4,positive,FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [3]:
df.columns

Index(['neutral', 'According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .'], dtype='object')

In [4]:
df.rename(columns={'neutral':'setiment','According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .':'text'}, inplace=True)

In [5]:
df.head()

   setiment                                               text
0   neutral  Technopolis plans to develop in stages an area...
1  negative  The international electronic industry company ...
2  positive  With the new production plant the company woul...
3  positive  According to the company 's updated strategy f...
4  positive  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [6]:
df.isnull().sum()

setiment    0
text        0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(6)

In [8]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [9]:
# data https://www.kaggle.com/datasets/clovisdalmolinvieira/news-sentiment-analysis

df1 = pd.read_csv("news_sentiment_analysis.csv")
df1.head()

,Source,Author,Title,Description,URL,Published At,Sentiment,Type
0,stgnews,Bridger Palmer,Pine View High teacher wins Best in State awar...,"ST. GEORGE — Kaitlyn Larson, a first-year teac...",https://www.stgeorgeutah.com/news/archive/2024...,2024-07-12T23:45:25+00:00,positive,Business
1,Zimbabwe Mail,Staff Reporter,Businesses Face Financial Strain Amid Liquidit...,"Harare, Zimbabwe – Local businesses are grappl...",https://www.thezimbabwemail.com/business/busin...,2024-07-12T22:59:42+00:00,neutral,Business
2,4-traders,NaN,Musk donates to super pac working to elect Tru...,(marketscreener.com) Billionaire Elon Musk has...,https://www.marketscreener.com/business-leader...,2024-07-12T22:52:55+00:00,positive,Business
3,4-traders,NaN,US FTC issues warning to franchisors over unfa...,(marketscreener.com) A U.S. trade regulator on...,https://www.marketscreener.com/quote/stock/MCD...,2024-07-12T22:41:01+00:00,negative,Business
4,PLANET,NaN,Rooftop solar's dark side,4.5 million households in the U.S. have solar ...,https://www.npr.org/2024/07/12/1197961036/roof...,2024-07-12T22:28:19+00:00,positive,Business

In [10]:
df1['Sentiment'].value_counts()

Sentiment
positive    2134
neutral      789
negative     577
Name: count, dtype: int64

In [11]:
df1 = df1[['Sentiment','Title','Type']]

In [12]:
df1 = df1[df1['Type'] == 'Business']

In [13]:
df1.drop('Type',axis=1,inplace=True)

In [14]:
df1.head()

  Sentiment                                              Title
0  positive  Pine View High teacher wins Best in State awar...
1   neutral  Businesses Face Financial Strain Amid Liquidit...
2  positive  Musk donates to super pac working to elect Tru...
3  negative  US FTC issues warning to franchisors over unfa...
4  positive                          Rooftop solar's dark side

In [15]:
df1.isnull().sum()

Sentiment    0
Title        0
dtype: int64

In [16]:
df1.duplicated().sum()

np.int64(146)

In [17]:
df1.drop_duplicates(inplace=True)

In [18]:
# data https://www.kaggle.com/datasets/aravsood7/sentiment-analysis-labelled-financial-news-data/data

df2 = pd.read_csv("Fin_Cleaned.csv")
df2.head()

,Date_published,Headline,Synopsis,Full_text,Final Status
0,2022-06-21,"Banks holding on to subsidy share, say payment...",The companies have written to the National Pay...,ReutersPayments companies and banks are at log...,Negative
1,2022-04-19,Digitally ready Bank of Baroda aims to click o...,"At present, 50% of the bank's retail loans are...",AgenciesThe bank presently has 20 million acti...,Positive
2,2022-05-27,Karnataka attracted investment commitment of R...,Karnataka is at the forefront in attracting in...,PTIKarnataka Chief Minister Basavaraj Bommai.K...,Positive
3,2022-04-06,Splitting of provident fund accounts may be de...,The EPFO is likely to split accounts only at t...,Getty ImagesThe budget for FY22 had imposed in...,Negative
4,2022-06-14,Irdai weighs proposal to privatise Insurance I...,"Set up in 2009 as an advisory body, IIB collec...",AgenciesThere is a view in the insurance indus...,Positive

In [19]:
df2 = df2[['Full_text','Final Status']]

In [20]:
df2.isnull().sum()

Full_text       0
Final Status    0
dtype: int64

In [21]:
df2.duplicated().sum()

np.int64(0)

In [22]:
print(df.columns)
print(df1.columns)
print(df2.columns)

Index(['setiment', 'text'], dtype='object')
Index(['Sentiment', 'Title'], dtype='object')
Index(['Full_text', 'Final Status'], dtype='object')

In [23]:
df1.rename(columns={'Sentiment':'setiment','Title':'text'},inplace=True)
df2.rename(columns={'Full_text':'text','Final Status':'setiment'},inplace=True)

In [24]:
df = pd.concat([df,df1,df2],axis=0)
df.head()

   setiment                                               text
0   neutral  Technopolis plans to develop in stages an area...
1  negative  The international electronic industry company ...
2  positive  With the new production plant the company woul...
3  positive  According to the company 's updated strategy f...
4  positive  FINANCING OF ASPOCOMP 'S GROWTH Aspocomp is ag...

In [25]:
df.setiment.value_counts()

setiment
neutral      2920
positive     1607
negative      666
Positive      215
Negative      184
Positive        1
Name: count, dtype: int64

In [26]:
df['setiment'] = df['setiment'].str.replace(' ','')

In [27]:
df['setiment'] = df['setiment'].str.replace('Positive','positive')
df['setiment'] = df['setiment'].str.replace('Negative','negative')

In [28]:
df.isnull().sum()

setiment    0
text        0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
df.drop_duplicates(inplace=True)

In [31]:
df.shape

(5593, 2)

handling imbalanced data

In [32]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=42)
x = df[['text']]      
y = df['setiment'] 
X_resampled, y_resampled = rus.fit_resample(x, y)

df = pd.concat([X_resampled,y_resampled],axis=1)
df = pd.DataFrame(df,columns=['text','setiment'])
df.head()

                                                  text  setiment
1    The international electronic industry company ...  negative
414  A tinyurl link takes users to a scamming site ...  negative
420  Compared with the FTSE 100 index , which rose ...  negative
422  Compared with the FTSE 100 index , which rose ...  negative
499  One of the challenges in the oil production in...  negative

In [33]:
df['setiment'].value_counts()

setiment
negative    850
neutral     850
positive    850
Name: count, dtype: int64

In [34]:
df.to_csv('final_data.csv',index=False)

In [35]:
df.shape

(2550, 2)