In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("final_data.csv")
df.sample(5)

                                                   text  setiment
2448  That topped consensus forecasts for earnings o...  positive
1802  In a release , the Company said that Vocollect...  positive
449   Device volume in the area decreased by 21 % to...  negative
2353  Sales increased due to growing market rates an...  positive
503   The Group 's order portfolio decreased from EU...  negative

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.isnull().sum()

text        0
setiment    0
dtype: int64

In [13]:
df.shape

(2550, 2)

In [14]:

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re

In [15]:
#text preprocessing


def preprocessing(text):
    ps = PorterStemmer()
    text = text.lower()
    text = re.sub('[0-9]+', '', text)
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub('[^a-zA-Z]',' ',text)
    text = [ps.stem(word) for word in text.split() if word not in set(stopwords.words('english'))]
    text = ' '.join(text)
    return text

In [16]:
df['text'] = df['text'].apply(preprocessing)

In [17]:
df.sample(5)

                                                   text  setiment
1583  nordea bank larg share vast experi nordic cred...   neutral
1899  one instal elev doubl deck elev enabl effici u...  positive
965   negoti concern personnel cencorp corpor singul...   neutral
1751  okmet product base high tech expertis gener ad...  positive
1959  agenciesemkay global financi servic buy call h...  positive

In [18]:
df.duplicated().sum()

np.int64(27)

In [19]:
df.drop_duplicates(inplace=True)

In [20]:
df.isnull().sum()

text        0
setiment    0
dtype: int64

In [21]:
df = df.dropna()
df.isnull().sum()

text        0
setiment    0
dtype: int64

In [22]:
df.to_csv("preprocessed_data.csv",index=False)

In [23]:
df.shape

(2523, 2)